import getCurrentUser from "@/actions/getCurrentUser";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import RegisterModal from "@/components/modals/RegisterModal";
import LoginModal from "@/components/modals/LoginModal";
import EditModal from "@/components/modals/EditModal";
import Layout from "@/components/Layout";
import ClientOnly from "@/components/ClientOnly";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  console.log(currentUser);
  return (
    <html lang="en">
      <ClientOnly>
        <Toaster />
        <RegisterModal />
        <LoginModal />
        {/*@ts-ignore*/}
        <EditModal currentUser={currentUser} />
      </ClientOnly>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
